### ISSUE TITLE
Add Jeffsum as a type

### ISSUE THREAD

**Issue by AlexHedley** [jsuarezruiz/VS4Mac-TextGenerator#1]
https://github.com/jamesmontemagno/Jeffsum.NET

**Comment by jsuarezruiz** [comment]
I'll keep it in mind. I think it's a good idea. Thank you!

**Comment by jsuarezruiz** [comment]
Functionality added in the PR: https://github.com/jsuarezruiz/VS4Mac-TextGenerator/pull/4
The v0.3 will include it!

Thanks for the feedback!

**Comment by AlexHedley** [comment]
Awesome :-)
